server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html index.htm;

    # Accesos al directorio raíz (ej: CSS, JS, etc.)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesamiento de archivos PHP
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        
        # Ocultar la versión de PHP por seguridad
        fastcgi_hide_header X-Powered-By;
    }

    # Denegar acceso a archivos ocultos (como .env)
    location ~ /\. {
        deny all;
    }
}
